### PR TITLE
Port setup.py to Gtk+3 and miscellaneous fixes

### LINKED ISSUE #5: No license metadata
`activity.info` does not have a license value.

### PR DESCRIPTION
**Pull request by yell0wfl4sh**
Fixes #5 #6 

Not sure whether #2 is still valid or not. @quozl

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed.

- [x] MathGraph32 is said to be GPLv3, please check my analysis and if so add the words ` and GPLv3+` to the license metadata.

Yes, #2 is still valid; Tony pointed out that there had been development here (18043bab8196b4e232c1bfd1e2bc83006e24422e) but no maintainer to release a new version.

However, there might be a newer version somewhere, see #9.

**Comment by yell0wfl4sh** [comment]
```activity.py``` and  ```setup.py``` state it to be GPLv2+, to be more sure I did ```git grep "GPL"```
result: https://paste.fedoraproject.org/paste/f4ZCEU056AAjhxhhNTQhBw

GPLv3+ is only mentioned in ```presentation.html``` and ```readme.txt``` , although MIT license also features in the result, not sure about its importance though.

**Comment by quozl** [comment]
Thanks.

Yes, `activity.py` and `setup.py` state themselves to be GPLv2+, but that's just those files, they don't infect the other files.

So an activity bundle made from this repository will be a multiple licensing scenario, and the metadata should say `GPLv2+ and GPLV3+`.

References:
* https://wiki.sugarlabs.org/go/Development_Team/Almanac/Activity_Bundles#.info_file_format
* https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#Multiple_Licensing_Scenarios

**Comment by yell0wfl4sh** [comment]
Thanks for explanation! :)

**Comment by yell0wfl4sh** [comment]
#2 can be taken care in another PR.

**Pull request merged**
